apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

images:
  - name: workshop-backend
    newName: workshop-backend
    newTag: local
  - name: workshop-frontend
    newName: workshop-frontend
    newTag: local

patches:
  - target:
      kind: Service
      name: backend
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30000
  - target:
      kind: Service
      name: frontend
    patch: |-
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30001
