apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ingress.yml

images:
  - name: workshop-backend
    newName: workshop-backend
    newTag: local
  - name: workshop-frontend
    newName: workshop-frontend
    newTag: local
