apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - base

images:
  - name: workshop-backend
    newName: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-backend
    newTag: v1.0

  - name: workshop-frontend
    newName: 196338543880.dkr.ecr.us-east-1.amazonaws.com/workshop-frontend
    newTag: v1.0
